### ISSUE TITLE
Rename fields and services endpoints for public api

### ISSUE THREAD

**Issue by danieleguido** [impresso/impresso-middle-layer#444]
> ‘article’ for us is a ‘content_item’. For alignment reasons, and also because having an article of type, e.g., advertisement or page is not so correct.
‘iiifFragment’:  “segment”  looks like a better choice, but I am not entirely sure of the object, to be discussed (both IIIF and computer vision communities use rather ‘segment’. Fragment meaning is also rather small, while an image segment can take up to a large part of the element it is a segment of.
‘iiif’: iiif alone is abit underspecified, even when there is the value, it would be best to have a more complete name. Here we can align with the canonical (we changed the naming, before was underspecified as well).

**Comment by danieleguido** [comment]
priority for pydantic function (maybe to hide for now) and aling with names

**Comment by theorm** [comment]
I suggest we rename the `article` endpoint and resource in the python library to `content_item` and handle iiif fields later. That's because the iiif fields are also used in the webapp and renaming them will require either changing the web app or duplicating fields (possibly in a smart way but with more code). We already have iiif covered in the schema. Perhaps we just deprecate the old fields and introduce new ones in the version after the release.
